### ISSUE TITLE
Missing idle status icon for Windows 7

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/brand-design#2]
`brand-design/Mockups/community_gui/prototype_two/tray_status_icons/` should have `idle coloured.svg`

**Comment by MeijeSibbel** [comment]
Merged, please close if it looks good.

**Comment by jkawamoto** [comment]
Thanks, but those are different icons. 

For example, [the error icon for Windows 7](https://github.com/GooBox/brand-design/blob/master/Mockups/community_gui/prototype_two/tray_status_icons/windows_icons/windows7/error%20(win7).svg) consists of light blue rounding boxes (semicircles) and a blue box, and they aren't touched. On the other hands, added icons, e.g. [idle color.svg](https://github.com/GooBox/brand-design/blob/master/Mockups/community_gui/prototype_two/tray_status_icons/idle%20color.svg), consist of same kinds of boxes but they are touched.

Do you have another icon which has some spaces between the boxes?

**Comment by MeijeSibbel** [comment]
Thanks, i will take care of this. I've emailed Luka and asked him if he could generate the remaining icons.

**Comment by MeijeSibbel** [comment]
They should be added now. Please confirm.

**Comment by jkawamoto** [comment]
Thanks. It has been added. I'll close this issue.
